# Generated by Django 4.0.1 on 2023-08-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_assistant_backend', '0003_taskorder_time_training_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='editing_end_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='editing_end_2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
