# Generated by Django 4.0.1 on 2023-08-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_assistant_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceAndAttitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProlificID', models.CharField(max_length=50, unique=True)),
                ('experience_1', models.CharField(max_length=2000, null=True)),
                ('thought_1', models.CharField(max_length=2000, null=True)),
                ('experience_2', models.CharField(max_length=2000, null=True)),
                ('thought_2', models.CharField(max_length=2000, null=True)),
                ('experience_3', models.CharField(max_length=2000, null=True)),
                ('thought_3', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProlificID', models.CharField(max_length=50, unique=True)),
                ('current', models.CharField(max_length=10)),
                ('order1', models.CharField(max_length=10)),
                ('order2', models.CharField(max_length=10)),
                ('order3', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=100, unique=True)),
                ('training_start_1', models.CharField(max_length=20, null=True)),
                ('training_start_2', models.CharField(max_length=20, null=True)),
                ('training_start_3', models.CharField(max_length=20, null=True)),
                ('training_end_1', models.CharField(max_length=20, null=True)),
                ('training_end_2', models.CharField(max_length=20, null=True)),
                ('training_end_3', models.CharField(max_length=20, null=True)),
                ('question_start_1', models.CharField(max_length=20, null=True)),
                ('question_start_2', models.CharField(max_length=20, null=True)),
                ('question_start_3', models.CharField(max_length=20, null=True)),
                ('question_end_1', models.CharField(max_length=20, null=True)),
                ('question_end_2', models.CharField(max_length=20, null=True)),
                ('question_end_3', models.CharField(max_length=20, null=True)),
                ('main_task_start_1', models.CharField(max_length=20)),
                ('main_task_start_2', models.CharField(max_length=20)),
                ('main_task_start_3', models.CharField(max_length=20)),
                ('main_task_end_1', models.CharField(max_length=20)),
                ('main_task_end_2', models.CharField(max_length=20)),
                ('main_task_end_3', models.CharField(max_length=20)),
                ('editing_start_1', models.CharField(max_length=20, null=True)),
                ('editing_start_2', models.CharField(max_length=20, null=True)),
                ('editing_start_3', models.CharField(max_length=20, null=True)),
                ('editing_end_1', models.CharField(max_length=20, null=True)),
                ('editing_end_2', models.CharField(max_length=20, null=True)),
                ('editing_end_3', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProlificID', models.CharField(max_length=50, unique=True)),
                ('training_1', models.CharField(max_length=2000)),
                ('training_2', models.CharField(max_length=2000)),
                ('training_3', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProlificID', models.CharField(max_length=50, unique=True)),
                ('condition', models.CharField(max_length=2000)),
                ('main_task_1', models.CharField(max_length=2000)),
                ('edited_message_1', models.CharField(max_length=2000)),
                ('main_task_2', models.CharField(max_length=2000)),
                ('edited_message_2', models.CharField(max_length=2000)),
                ('main_task_3', models.CharField(max_length=2000)),
                ('edited_message_3', models.CharField(max_length=2000)),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='pwd',
        ),
    ]
